### PR TITLE
- Apply integrant library for flexible broker configuration.

### PR DESCRIPTION
**Pull request by ghost**
- For varying server configuration, trying to add like ":profiles {{profile-name} {:env {:config-file {config-file-name}" in project.clj and write configuration in {config-file-name}
- Rename s.clj to interfaces which shares *server* value.

### CODE REVIEW

**Comment by thomas-shares** [comment]
When I start the server from the REPL I am getting this error on the first CONNECT:
```
java.lang.NullPointerException
Can't RUN!!! null {:clean-session? true, :client-id "mosq-I72tyUQBaiDOlu5UUV", :client-key #object[sun.nio.ch.SelectionKeyImpl 0x7472a8a3 "sun.nio.ch.SelectionKeyImpl@7472a8a3"], :keep-alive 5, :packet-type :CONNECT, :protocol-name "MQTT", :protocol-version 4}
	at mqttkat.handlers$send_buffer.invokeStatic(handlers.clj:74)
	at mqttkat.handlers$send_buffer.invoke(handlers.clj:69)
	at mqttkat.handlers.connect$handle_success.invokeStatic(connect.clj:40)
	at mqttkat.handlers.connect$handle_success.invoke(connect.clj:35)
	at mqttkat.handlers.connect$connect.invokeStatic(connect.clj:53)
```
I suspect this is due to the server being NULL, but haven't investigated this any further (yet)

Also when I build a ```lein uberjar``` I get an error on starting the server. It looks like the config is missing somehow.

Otherwise I do like the changes. It makes it much more of a proper server! Thank you.

**Comment by ghost** [comment]
I will fix and commit again.

**Comment by ghost** [comment]
While fixing error of this issue, I thought that the request handling functions return response handling function is better than directly processing response to sending. It could be reducing atomic value such as *server* or *system*.

for example, 

```
(defn send-buffer [keys buf]
  (update-timestamps keys)
  (let [{s :server} (meta @*server*)]
    (.sendMessageBuffer ^MqttServer s keys buf)))

```
from above changes to belows : 

```
(defn send-buffer [keys buf]
  (update-timestamps keys)
  (fn [server]
    (.sendMessageBuffer ^MqttServer server keys buf)))


```

**Comment by thomas-shares** [comment]
@jocatelo  these changes look good and if you need help with the merge conflict let me know.

**Pull request closed without merging**
